using DataArc.ObservR.Abstractions;

using EShop.Domain.Ordering.Policies.Context;
using EShop.Domain.Ordering.Policies.Contracts;
using EShop.Domain.Ordering.ValueObjects;
using EShop.Domain.Ordering.Enums;

using EShop.Features.Ordering.Interfaces;
using EShop.UseCases.Ordering.Contracts.Input;

using EShop.UseCases.Ordering.Dtos;
using EShop.UseCases.Ordering.Ports;

namespace EShop.Features.Ordering.Services
{
    public class OrderingService(
        IOrderingPort orderingPort,
        ICreateOrderPolicy createOrderPolicy,
        IObservableEventHandler observableEventHandler) : IOrderingService
    {
        public async Task<OrderDto> CreateOrder(CreateOrderInput input)
        {
            //Build Address VO
            var address = new AddressValueObject(
                input.Street,
                input.City,
                input.State,
                input.Country,
                input.ZipCode
            );

            //Build Order VO (DDD-correct version)
            var order = new OrderValueObject(
                buyerId: null,                 
                paymentId: null,               
                address: address,
                orderStatus: OrderStatus.Submitted,
                description: "Order Submitted",
                orderDate: DateTime.UtcNow
            );

            //Create policy context
            var policyContext = new CreateOrderPolicyContext(order, address);

            //Evaluate business rule
            var policyResult = createOrderPolicy.Apply(policyContext);

            //Handle success case
            if (policyResult.IsSuccess)
            {
                var result = await orderingPort.CreateOrderAsync(input);

                //Fire domain events generated by policy
                await observableEventHandler.DispatchAsync(policyResult.DomainEvents);

                return result.OrderDto;
            }

            //Handle failure case (still dispatch domain events)
            await observableEventHandler.DispatchAsync(policyResult.DomainEvents);
            return new OrderDto();
        }

        public Task<List<OrderDto>> GetOrders()
        {
            throw new NotImplementedException();
        }
    }
}